version: '3.8'

services:
  vanilla-app:
    build: .
    image: crpi-goo4z49jdymjsvdp.cn-hangzhou.personal.cr.aliyuncs.com/nh_vanilla/python:3.12-slim
    container_name: vanilla-app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    # 如果需要直接访问应用，可以取消下面的注释
    ports:
      - "8000:8000"

  nginx:
    image: crpi-goo4z49jdymjsvdp.cn-hangzhou.personal.cr.aliyuncs.com/nh_vanilla/nginx:latest
    container_name: vanilla-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - vanilla-app
